arogozhnikov/einops

einops/_backends.py

When running in graph mode, TensorFlow tensors have two types of shapes:
- a static shape, known when the graph is built
- a dynamic shape, only known when the graph is run
The static shape is important especially for the channels dimension, since the number of variables needed for a convolution depends on this shape.
In the current implementation, `einops` uses only the dynamic shape in graph execution mode, which means that static shape information is lost after calling one of the einops functions. I have updated the TensorFlow backend to only use dynamic shape information for dimensions where the static shape is unknown.

Use static shape where available in TensorFlow backend

---

einops/_backends.py

this time mxnet maintainers broke zero-size variables

Fix for emtpy-shaped variables in mxnet

---

README.md

This actually raises a question - does einops check for unused arguments to prevent errors like these?

Fix copy paste typo in the readme usage examples

---

.travis.yml
einops/_backends.py
einops/einops.py
einops/layers/keras.py
test.py
tests/__init__.py
tests/test_layers.py

- adjustments for tf being in eager mode by default
- more stable shape inference for tf symbols
- deprecate keras layers
- single run of tests (previously had to run independently for eager and non-eager modes)

Refactor tests

---

einops/__init__.py

`'repeat'` was missing from the `__all__` list in `__init__.py` even though it's imported. Some IDEs (e.g. PyCharm) treat it as warning. This is a very minor fix.

Add 'repeat' to import __all__

---

einops/einops.py
einops/parsing.py
tests/test_other.py

This implementation reuses the machinery of `ParsedExpression` to ensure that the patterns are parsed the same for all the functions in the API of einops.
I had to add a new option `allow_underscore` to the `ParsedExpression`.
Fixes #158

Reject repeated axes in parse_shape

---

einops/einops.py
test.py
tests/test_other.py

Now parse_shape can accept ellipsis the same as other operations.
For example,
`parse_shape(np.zeros((10, 20, 30, 40)), 'a ... b')`
returns
`dict(a=10, b=40)`
TODO:
Fixes #161

[WIP] Enable ellipsis in patterns for parse_shape.

---

einops/_backends.py
einops/layers/oneflow.py
test.py
tests/__init__.py
tests/test_einsum.py
tests/test_examples.py
tests/test_ops.py
tests/test_other.py

Hello! I try to add OneFlow backend into einops, here's my PR~
- How should I do some tests based on the new Backend? I've already do some simple tests based on the basic usage of einops and all of them worked, but how should I do some official tests on more cases~

Add oneflow backend

---

einops/__init__.py
einops/_backends.py
einops/einops.py
einops/parsing.py
tests/test_einsum.py

This creates the functional einsum function as requested on #73. CC @arogozhnikov @cgarciae 
The current implementation simply parses the string and converts it to `einsum` notation by mapping axis names to single characters (I use `string.ascii_letters`, starting from `a, b, c` etc).
Currently, it has the following features:
- Supports the backends: tensorflow, numpy, jax, pytorch, chainer, oneflow, keras, cupy.
- Allows for an arbitrary number of tensors passed.
- Allows ellipsis specification, including for multiple tensors, so long as it is provided on both the left and the right of the `->`.
It does not currently support
- Reshape operations, such as `"(batch channel) feature, feature -> batch channel"`.
- Custom reduction operations.
These could be added later if desired. Some …

Create einsum operation

---

einops/layers/_einmix.py

The default value of `None` for the `bias_shape` parameter has an ambiguous meaning: either "inferred" or "no bias". So here's a clarification for that.

Clarify documentation re. default bias on EinMix

---

docs/2-einops-for-deep-learning.ipynb

Correcting a small typo in `2-einops-for-deep-learning.ipynb`

corrected spelling mistake: einsops -> einops

---

einops/einops.py

The example wasn't doing "repeat image 2 time along height" previously.

Update example to match description

---

.github/workflows/run_tests.yml
einops/_backends.py
einops/layers/paddle.py
pyproject.toml
test.py
tests/__init__.py
tests/test_einsum.py
tests/test_examples.py
tests/test_layers.py
tests/test_notebooks.py
tests/test_ops.py
tests/test_other.py

- backend for paddle was added
- testing now can specify which frameworks to test, and tests have simpler utilties
- started adopting black + pylance for style/type warnings
- multiple tests now depend on backend being tested
- in CI frameworks are split into two groups because of protobuf conflicts

Add paddle backend, rewrite testing infrastructure

---

einops/array_api.py
einops/einops.py
tests/test_ops.py
tests/test_packing.py

Einops implements a basic set of operations based on array api:
```
from einops.array_api import rearrange, reduce, repeat, asnumpy, pack, unpack
```
cc: @shoyer @rgommers

Support array api 

---

einops/_backends.py
einops/_torch_specific.py

registration happens in either of cases:
1. explicit import of _torch_specific
1. einops operation is used on torch tensor (this triggers instantiation of TorchBackend which imports _torch_specific)
1. usage of any torch layer

automatically register torch ops in torchdynamo

---

test.py
tests/test_other.py

previous conventions were broken and pypi be default installs cuda version.

tests: fix torch installation to force CPU

---

einops/packing.py

While trying to use torch.compile with `backend=inductor` for a model that uses unpack as 
```
unpack(x, ps, "b d *")[0]
```
I received the error 
```
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <function unpack at 0x7f5c30806200>(*(FakeTensor(..., device='cuda:0', size=(1, 128, (s1//2))), [((s1//2),)], 'b d *'), **{}):
unsupported operand type(s) for +: 'int' and 'SymBool'
```
tracing back to the line changed in this PR. Coercing the boolean to an int so `sum` does not try to sum a boolean and an int fixed my issue locally.

Coerce bool to int in unpack

---

einops/einops.py

Current einsum docstring has an invalid escape sequence, specifically in the `\sum` for some LaTeX code. This can be checked by running the following:
```bash
$ PYTHONWARNINGS=error python -c "import einops"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "~/.venv/lib/python3.10/site-packages/einops/__init__.py", line 14, in <module>
from .einops import rearrange, reduce, repeat, einsum, parse_shape, asnumpy
File "~/.venv/lib/python3.10/site-packages/einops/einops.py", line 827
"""
^^^
SyntaxError: invalid escape sequence '\s'
```
This can be annoying, especially when running tests if one wants to run them in strict mode (warnings-as-errors) Replacing with a raw docstring removes the issue.

Fix invalid escape sequence in einsum docstring

---

.devcontainer/devcontainer.json
.devcontainer/einops.Dockerfile
pyproject.toml

motivation: 
fastest way to have ~isolated environment that is ~compatible to CI and has pre-commits turned on by default.
Confirmed this works right from github interface:
```shell
python test.py numpy
hatch run docs:build
```
fix #328

Add devcontainer and dockerfile

---

docs/2-einops-for-deep-learning.ipynb

This patch adds an example of the dict syntax that is given as argument in einops layers.
**Why do we need this change?**
I was trying to make an einops layer doing the following rearrange:
```python
Rearrange('b (h w c) -> b h w c', h=64, w=64)
```
And had to read the source code to discover I have to use dict syntax to make it works:
```python
Rearrange('b (h w c) -> b h w c', {'h'=64, 'w'=64})
```
So I believe that adding this example to the docs will make it easier for people like me

Add dict syntax to the einops layers example

---

CITATION.cff

Adding a CITATION.cff enables GitHub and other apps to automatically detect the correct way to cite mlx. This file contains the same semantic content as the BibTex citation in the README. You can take a look at how other repos implement their CITATION.cff for more info, like [pytorch/CITATION.cff](https://github.com/pytorch/pytorch/blob/main/CITATION.cff)
It also adds new views on the GitHub site, for example:

include CITATION.cff for einops

---

README.md
docs/1-einops-basics.ipynb
docs/README.md
docs/pytorch-examples.html
einops/layers/_einmix.py
scripts/pytorch_examples_source/Pytorch.ipynb

Minor fix of documentation links that became broken after `master` -> `main` migration.
GitHub does automatic redirects of the current `master` links, but nbviewer doesn't - displays 404 for all links from [`arogozhnikov/einops/blob/main/docs/README.md`](https://github.com/arogozhnikov/einops/blob/main/docs/README.md)
PR consistently renames all leftover `master` mentions to `main`, so all links work as expected.

Fix docs broken links after `master` -> `main` migration

---

einops/_backends.py

Use paddle.is_tensor instead of isinstance to support `pir.Value` type when exporting model which use einops in computation
Related issue: <https://github.com/PaddlePaddle/PaddleScience/issues/1035>

[Paddle] Update _backends.py to support pir.Value

---

einops/layers/_einmix.py
einops/tests/test_layers.py

this update makes it possible to use ellipsis in einmix patterns, for example this layer can handle inputs with >= 1 dimensions:
```python
EinMix("... (h c_in) -> ... (h c_out)", weight_shape='h c_in c_out", ...)
```

Add support of ellipsis to einmix

---

.github/workflows/run_tests.yml
README.md
einops/_backends.py
einops/tests/__init__.py
einops/tests/run_tests.py
einops/tests/test_einsum.py
einops/tests/test_other.py

Hi!
I understand that the library is moving away from specific backends in favor of the array api standard, but this was so much easier for us to implement and test.
From a first glance the array api standard compatibility suite seems completely oblivious to lazy backends right now. Will  double check and open an issue with them later if my suspicion is correct.
This also seems to test part of the test codebase that was untested since the drop of MxNet (?). Fixed two errors there.
Happy to remove PyTensor from the test suite if that's a drag / blocker. Not sure if we could test it from our CI as some of these test options are hardcoded in the library? Sounds like it should be easy to make them customizable though?
~~Currently all tests pass except the 3 tensor einsum multiplication. Issue …

Add PyTensor backend
