.travis.yml, README.md, einops/backends.py, test.py, test.sh, tests/test_ops.py, tests/test_other.py
Tests are with python 3.5 and 3.6
- Doctests are skipped for 3.5
- Numpy.einsum tests skipped for older numpy versions (tensorflow blocks updating)
=> Add travis-CI, fix #1

tests/test_layers.py
fixes #8, as expected no changes required
=> Add testing of model freezing for pytorch

tests/test_ops.py
Related to #7 
- mxnet doesn't support reduction on numerous axes and tranposition for 7 axes or more
This is right now skipped in testing
=> exception in tests for mxnet 

docs/1-einops-basics.ipynb
- "or compose a new dimension of batch and height" -> and width (and height was done the line before)
=> English typos

README TensorFlow.md, einops/layers/tensorflow.py
I love your project, it has really changed the way I write my code. I wanted to be able to use it in the TensorFlow version of Keras as well. I only had to change one thing since the dimensions are represented differently.
=> tensorflow layers

einops/einops.py
I tried to use median and the error msg was not helpful (Typo or unsupported).
This PR adds the available reductions to the exception msg.
=> Improve Unknown reduction error msg

.travis.yml, einops/_backends.py, test.py
- docker environment
- all the installation moved inside test.py
- python 3.7 added instead of 3.6
Testing time seems to be uninfluenced
=> Update CI tests

einops/_backends.py
(the critical difference spotted is removal of tf.cotrib)
=> Update to support tensorflow 2

einops/_backends.py
Added support for https://github.com/google/jax by subclassing the existing numpy backend. I also had to modify the way backends are discovered as before it would only discover immediate subclasses of `AbstractBackend`.
=> Added jax support

README.md
Hello,
Thank you for the great work. This pull request aims to improve the project's documentation specifically the README file.
Best,
Nelson
=> Grammar improvements

einops/einops.py, tests/test_ops.py
Fix #60 
Relevant questions: #28 #29
=> Add support for anonymous axes 

einops/einops.py, tests/test_ops.py
=> Support for passing functions in reduce rather than strings

docs/1-einops-basics.ipynb, docs/pytorch-examples.html, docs/source_examples/Pytorch.ipynb, einops/_backends.py, tests/test_ops.py
=> spelling corrections

einops/_torch_specific.py, einops/einops.py, einops/layers/__init__.py, einops/layers/keras.py, einops/layers/tensorflow.py, einops/layers/torch.py, einops/parsing.py, tests/test_layers.py
=> Add support for torch scripting of einops layers

docs/3-einmix-layer.ipynb, einops/layers/_einmix.py, einops/layers/_weighted_einsum.py, einops/layers/chainer.py, einops/layers/gluon.py, einops/layers/keras.py, einops/layers/tensorflow.py, einops/layers/torch.py, einops/parsing.py, tests/test_einsum.py, tests/test_layers.py
tutorial: https://einops.rocks/3-einmix-layer/
=> Introduce EinMix - swiss-knife for next-gen MLPs

einops/einops.py
https://github.com/arogozhnikov/einops/issues/175
=> fix numpy dependency problem

einops/_backends.py, einops/layers/oneflow.py, test.py, tests/__init__.py, tests/test_einsum.py, tests/test_examples.py, tests/test_ops.py, tests/test_other.py
adjustments of testing setup to accomodate PR #180.
=> Add oneflow backend

einops/einops.py
=> Fix wrong error message

einops/_backends.py, einops/einops.py, test.py, tests/__init__.py, tests/test_notebooks.py, tests/test_other.py
as previously announced in v0.6.0, support for mxnet is dropped in the next versions
=> Remove mxnet

einops/_backends.py, einops/layers/paddle.py, test.py, tests/__init__.py, tests/test_einsum.py, tests/test_examples.py, tests/test_ops.py
Add PaddlePaddle backend for einops
=> Add PaddlePaddle backend for einops

.github/workflows/run_tests.yml, test.py, tests/test_other.py
see https://github.com/Oneflow-Inc/oneflow/issues/10340 for details
=> Remove oneflow from testing

einops/experimental/indexing.py, tests/test_ops.py, tests/test_packing.py
see https://github.com/numpy/numpy/issues/27137 for details on array api incompatibility
=> change tests for numpy2.0 + fix for numpy regression 

.gitignore, README.md
additional: gardening of gitignore
=> Mention support of cupy, pydata/sparse, ndonnx and others

.github/workflows/deploy_docs.yml, README.md, einops/einops.py, mkdocs.yml, pyproject.toml
- clean up + update mkdocs requirements
- setup autodeploy
fix #331
=> Auto-deploy mkdocs + update mkdocs requirements

einops/einops.py
As noted in #357 , some of reductions were missing in the list
=> Update docstring for einops.reduce

einops/_backends.py
rename parameter per discussion in #362
=> rename input_dict, document parameter
